site_name: Forensic Examiner
site_description: The Swiss Army Knife for examining text files.
site_author: Christian Uhsat
site_url: https://forensic-examiner.eu/

repo_name: github.com/cuhsat/fox
repo_url: https://github.com/cuhsat/fox

remote_branch: docs

copyright: © 2025 Soli Deo Gloria

markdown_extensions:
  - admonition
  - attr_list

nav:
  - Home: index.md

  - Getting started:
    - Tutorial: start/tutorial.md
    - Install: start/install.md
    - Usage: start/usage/usage.md

  - Features:
    - Filesystem: features/filesystem.md
    - Evidence: features/evidence.md

    - AI:
      - Assistant: features/ai/assistant.md

  - Files:
    - Loader: files/loader.md

    - Text:
      - JSON: files/text/json.md

    - Logs:
      - Linux: files/logs/linux.md
      - Windows: files/logs/windows.md

  - Plugins:
    - Configuration: plugins/config.md

    - Ready-made:
      - Dissect: plugins/ready/dissect.md
      - Eric Zimmerman: plugins/ready/eztools.md
      - Sleuth Kit: plugins/ready/sleuth.md
      - Various logs: plugins/ready/logs.md
      - Various tools: plugins/ready/tools.md

  - Resources:
    - Building: resources/building.md
    - License: resources/license.md

theme:
  name: material
  logo: fox.svg

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github
    admonition:
      tip: fontawesome/solid/lightbulb

  favicon: fox.ico

  features:
    - content.code.copy
    - content.code.select
    - toc.follow
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight
    - search.suggest

  palette:
    primary: custom
    accent: custom

extra:
  homepage: https://forensic-examiner.eu
  generator: false

  social:
    - icon: fontawesome/solid/envelope
      link: mailto:christian@uhsat.de
      name: Mail

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cuhsat
      name: LinkedIn

    - icon: fontawesome/brands/github
      link: https://github.com/cuhsat
      name: GitHub

extra_css:
  - assets/css/fox.css

plugins:
  - search
  - privacy
  - offline
